namespace TaxService.Models;

public abstract record TaxJarResult
{
    public string? geoPostalCode { get; set; }
    public string? geoCounty { get; set; }
    public string? geoState { get; set; }
    public decimal? taxSales { get; set; }
    public decimal? taxUse { get; set; }
    public string? txbService { get; set; }
    public string? txbFreight { get; set; }
}

/*
//v20
            "geoPostalCode": "33172",
            "geoCity": "DORAL",
            "geoCounty": "MIAMI-DADE",
            "geoState": "FL",
            "taxSales": 0.07,
            "taxUse": 0.07,
            "txbService": "L",
            "txbFreight": "Y",
            "stateSalesTax": 0.06,
            "stateUseTax": 0.06,
            "citySalesTax": 0,
            "cityUseTax": 0,
            "cityTaxCode": "",
            "countySalesTax": 0.01,
            "countyUseTax": 0.01,
            "countyTaxCode": "23",
            "districtSalesTax": 0,
            "districtUseTax": 0



{
    "version": "v40",
    "rCode": 100,
    "results": [
        {
            "geoPostalCode": "33172",
            "geoCity": "DORAL",
            "geoCounty": "MIAMI-DADE",
            "geoState": "FL",
            "taxSales": 0.07,
            "taxUse": 0.07,
            "txbService": "L",
            "txbFreight": "Y",
            "stateSalesTax": 0.06,
            "stateUseTax": 0.06,
            "citySalesTax": 0,
            "cityUseTax": 0,
            "cityTaxCode": "",
            "countySalesTax": 0.01,
            "countyUseTax": 0.01,
            "countyTaxCode": "23",
            "districtSalesTax": 0,
            "districtUseTax": 0,
            "district1Code": "",
            "district1SalesTax": 0,
            "district1UseTax": 0,
            "district2Code": "",
            "district2SalesTax": 0,
            "district2UseTax": 0,
            "district3Code": "",
            "district3SalesTax": 0,
            "district3UseTax": 0,
            "district4Code": "",
            "district4SalesTax": 0,
            "district4UseTax": 0,
            "district5Code": "",
            "district5SalesTax": 0,
            "district5UseTax": 0,
            "originDestination": "D"
        },
        {
    "geoPostalCode": "33172",
            "geoCity": "MIAMI",
            "geoCounty": "MIAMI-DADE",
            "geoState": "FL",
            "taxSales": 0.07,
            "taxUse": 0.07,
            "txbService": "L",
            "txbFreight": "Y",
            "stateSalesTax": 0.06,
            "stateUseTax": 0.06,
            "citySalesTax": 0,
            "cityUseTax": 0,
            "cityTaxCode": "",
            "countySalesTax": 0.01,
            "countyUseTax": 0.01,
            "countyTaxCode": "23",
            "districtSalesTax": 0,
            "districtUseTax": 0,
            "district1Code": "",
            "district1SalesTax": 0,
            "district1UseTax": 0,
            "district2Code": "",
            "district2SalesTax": 0,
            "district2UseTax": 0,
            "district3Code": "",
            "district3SalesTax": 0,
            "district3UseTax": 0,
            "district4Code": "",
            "district4SalesTax": 0,
            "district4UseTax": 0,
            "district5Code": "",
            "district5SalesTax": 0,
            "district5UseTax": 0,
            "originDestination": "D"
        },
        {
    "geoPostalCode": "33172",
            "geoCity": "SWEETWATER",
            "geoCounty": "MIAMI-DADE",
            "geoState": "FL",
            "taxSales": 0.07,
            "taxUse": 0.07,
            "txbService": "L",
            "txbFreight": "Y",
            "stateSalesTax": 0.06,
            "stateUseTax": 0.06,
            "citySalesTax": 0,
            "cityUseTax": 0,
            "cityTaxCode": "",
            "countySalesTax": 0.01,
            "countyUseTax": 0.01,
            "countyTaxCode": "23",
            "districtSalesTax": 0,
            "districtUseTax": 0,
            "district1Code": "",
            "district1SalesTax": 0,
            "district1UseTax": 0,
            "district2Code": "",
            "district2SalesTax": 0,
            "district2UseTax": 0,
            "district3Code": "",
            "district3SalesTax": 0,
            "district3UseTax": 0,
            "district4Code": "",
            "district4SalesTax": 0,
            "district4UseTax": 0,
            "district5Code": "",
            "district5SalesTax": 0,
            "district5UseTax": 0,
            "originDestination": "D"
        },
        {
    "geoPostalCode": "33172",
            "geoCity": "WEST MIAMI",
            "geoCounty": "MIAMI-DADE",
            "geoState": "FL",
            "taxSales": 0.07,
            "taxUse": 0.07,
            "txbService": "L",
            "txbFreight": "Y",
            "stateSalesTax": 0.06,
            "stateUseTax": 0.06,
            "citySalesTax": 0,
            "cityUseTax": 0,
            "cityTaxCode": "",
            "countySalesTax": 0.01,
            "countyUseTax": 0.01,
            "countyTaxCode": "23",
            "districtSalesTax": 0,
            "districtUseTax": 0,
            "district1Code": "",
            "district1SalesTax": 0,
            "district1UseTax": 0,
            "district2Code": "",
            "district2SalesTax": 0,
            "district2UseTax": 0,
            "district3Code": "",
            "district3SalesTax": 0,
            "district3UseTax": 0,
            "district4Code": "",
            "district4SalesTax": 0,
            "district4UseTax": 0,
            "district5Code": "",
            "district5SalesTax": 0,
            "district5UseTax": 0,
            "originDestination": "D"
        }
    ]
}
*/